name: bstock_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  go_router: ^16.0.0
  shared_preferences: ^2.2.3
  mobile_scanner: ^5.2.3
  intl: ^0.20.2
  url_launcher: ^6.3.2
  file_picker: ^10.2.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 